#!/bin/bash

set -e

# This folder is used by Mono to store created key value pairs
# Which is used by Jackett for encryption.
# Keeping this folder in configuration allows Jackett to keep its
# configured encryption information even when the docker container
# is deleted and re-created
if [ ! -d /config/nonexistent ]; then
	mkdir /config/nonexistent
	chown -R nobody:nogroup /config/nonexistent
	chmod -R 700 /config/nonexistent
fi

if [ ! -d /nonexistent ]; then
	ln -s /config/nonexistent /nonexistent
fi
chown -R nobody:nogroup /nonexistent
chmod -R 700 /nonexistent
