#!/bin/bash
LIST=$(find /etc/apt/sources.list.d -name "*transmission*.list" -type f -printf "%f")
apt-get update \
	-o Dir::Etc::sourcelist="sources.list.d/$LIST" \
	-o Dir::Etc::sourceparts="-" \
	-o APT::Get::List-Cleanup="0"
apt-get install -qy --no-install-recommends transmission-cli transmission-daemon transmission-common
